---
# Inventario de servidores para la aplicación TODO
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
    appservers:
      hosts:
        app01:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
    databases:
      hosts:
        db01:
          ansible_host: 192.168.1.12
          ansible_user: ubuntu

  vars:
    # Variables globales
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
