---
# Playbook para configurar servidor de aplicación Flask
- name: Configurar servidor de aplicación Flask
  hosts: appservers
  become: yes
  gather_facts: yes

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Instalar Python y dependencias del sistema
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
          - libpq-dev
        state: present
      when: ansible_os_family == "Debian"

    - name: Crear directorio de la aplicación
      file:
        path: "/opt/todo-app"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copiar código de la aplicación
      copy:
        src: ../app/
        dest: "/opt/todo-app/"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Crear entorno virtual de Python
      command: python3 -m venv /opt/todo-app/venv
      args:
        creates: "/opt/todo-app/venv/bin/activate"
      become_user: www-data

    - name: Actualizar pip en el entorno virtual
      pip:
        name: pip
        state: latest
        virtualenv: "/opt/todo-app/venv"
      become_user: www-data

    - name: Instalar dependencias de Python
      pip:
        requirements: "/opt/todo-app/requirements.txt"
        virtualenv: "/opt/todo-app/venv"
      become_user: www-data

    - name: Crear archivo de servicio systemd para Gunicorn
      copy:
        src: ../files/todo-app.service
        dest: /etc/systemd/system/todo-app.service
      notify:
        - reload systemd
        - restart gunicorn

    - name: Habilitar y iniciar servicio de Gunicorn
      systemd:
        name: todo-app
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Abrir puerto de la aplicación en firewall (si está activo)
      ufw:
        rule: allow
        port: "5000"
        proto: tcp
      ignore_errors: yes

    - name: Verificar que la aplicación esté respondiendo
      uri:
        url: "http://localhost:5000/health"
        method: GET
        status_code: 200
      retries: 5
      delay: 10

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart gunicorn
      systemd:
        name: todo-app
        state: restarted
