---
# Playbook principal para desplegar la aplicación TODO completa
- name: Desplegar aplicación TODO de 3 capas
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Mostrar información del despliegue
      debug:
        msg:
          - "=== Iniciando despliegue de aplicación TODO ==="
          - "Arquitectura: Frontend (Nginx) → Backend (Flask) → Database (PostgreSQL)"
          - "Servidores web: {{ groups['webservers'] }}"
          - "Servidores app: {{ groups['appservers'] }}"
          - "Servidores DB: {{ groups['databases'] }}"

# Paso 1: Configurar base de datos
- import_playbook: database.yml

# Paso 2: Configurar servidor de aplicación
- import_playbook: appserver.yml

# Paso 3: Configurar servidor web
- import_playbook: webserver.yml

# Paso 4: Verificación final
- name: Verificación final del despliegue
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Esperar a que todos los servicios estén listos
      pause:
        seconds: 10
        prompt: "Esperando a que todos los servicios se inicializen..."

    - name: Verificar conectividad de la base de datos
      postgresql_ping:
        db: "todoapp"
        login_host: "192.168.1.12"
        login_user: "todouser"
        login_password: "todopass123"
      delegate_to: "{{ groups['databases'][0] }}"

    - name: Verificar API del backend
      uri:
        url: "http://192.168.1.11:5000/health"
        method: GET
        status_code: 200
      register: backend_health

    - name: Verificar frontend web
      uri:
        url: "http://192.168.1.10:80/"
        method: GET
        status_code: 200
      register: frontend_health

    - name: Mostrar resultado del despliegue
      debug:
        msg:
          - "=== DESPLIEGUE COMPLETADO EXITOSAMENTE ==="
          - "🗄️  Base de datos: PostgreSQL en 192.168.1.12:5432"
          - "⚙️  Backend API: Flask en 192.168.1.11:5000"
          - "🌐 Frontend: Nginx en 192.168.1.10:80"
          - ""
          - "🚀 Accede a la aplicación en: http://192.168.1.10"
          - ""
          - "Endpoints disponibles:"
          - "  - /              → Interfaz web principal"
          - "  - /api/tasks     → API REST de tareas"
          - "  - /health        → Estado del backend"
          - "  - /nginx-health  → Estado del frontend"
