---
# Playbook para configurar servidor web Nginx
- name: Configurar servidor web Nginx
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Crear directorio web root
      file:
        path: "/var/www/html"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Crear directorio para archivos estáticos
      file:
        path: "/var/www/html/static"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Configurar Nginx
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify: restart nginx

    - name: Eliminar configuración por defecto de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Verificar configuración de Nginx
      command: nginx -t
      register: nginx_syntax
      changed_when: false

    - name: Mostrar resultado de verificación de Nginx
      debug:
        var: nginx_syntax.stdout_lines

    - name: Habilitar y iniciar Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Abrir puerto HTTP en firewall (si está activo)
      ufw:
        rule: allow
        port: "80"
        proto: tcp
      ignore_errors: yes

    - name: Verificar que Nginx esté respondiendo
      uri:
        url: "http://localhost:80/nginx-health"
        method: GET
        status_code: 200
      retries: 5
      delay: 5

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
